---
# tasks file for App
- name: Create app Secret with MySQL credentials
  community.kubernetes.k8s:
     definition:
        kind: Secret
        apiVersion: v1
        metadata:
          name: nodejs-secret
          namespace: default
        type: Opaque
        data:
         root-username: cm9vdA==
         root-password: YmJwbTE5OTg=
- name: Create ConfigMap
  community.kubernetes.k8s:
     definition:
        kind: ConfigMap
        apiVersion: v1
        metadata:
          name: nodejs-configmap
          namespace: default
        data:
         database: EmployeeDB
         host: mysql
- name: Create node service
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: nodejs-service
        namespace: default
      spec:
       type: NodePort
       selector:
         app: nodejs
       ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
- name: Create node deployment
  community.kubernetes.k8s:
    definition:
       apiVersion: apps/v1
       kind: Deployment
       metadata:
         name: nodejs-deployment
         namespace: default
         labels:
           app: nodejs
       spec:
         replicas: "{{size}}"
         selector:
           matchLabels:
              app: nodejs
         template:
            metadata:
               labels:
                  app: nodejs
            spec:
             containers:
              - name: nodejs
                image: "docker.io/bilwamoye/myemployeeapi:latest"
                env:
                 - name: DB_HOST
                   valueFrom:
                     configMapKeyRef:
                      name: nodejs-configmap
                      key: host
                 - name: DB_USER
                   valueFrom:
                    secretKeyRef:
                     name: nodejs-secret
                     key: root-username
                 - name: DB_PASSWORD
                   valueFrom:
                    secretKeyRef:
                     name: nodejs-secret
                     key: root-password
                 - name: MYSQL_DB
                   valueFrom:
                    configMapKeyRef:
                     name: nodejs-configmap
                     key: database
                ports:
                - containerPort: 3000
